language: python
cache: pip
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - travis_retry pip install -r requirements.txt
  - make
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.4'* && $TRAVIS_PYTHON_VERSION != '3.5'* ]]; then
      git diff --exit-code apertium-init.py;
    fi
  - flake8 *.py **/*.py
  - mypy --strict *.py
notifications:
  on_failure: change
  on_success: change
