language: python
cache: pip
sudo: required
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - pip install pipenv
  - travis_retry pipenv install --dev --system
  - make
before_script:
  - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
  - sudo apt-get -f --allow-unauthenticated install apertium-all-dev
script:
  - make test
after_success:
    - coveralls
notifications:
  on_failure: change
  on_success: change
